09:34:36 PM: DEBUG [Empleado.py: 63] 
                ID Empleado: 1
                Usuario: pepe
                Nombre(s) = José
                Apellido Paterno: Flores
                Apellido Materno: Alvarado
                
09:35:34 PM: DEBUG [Empleado.py: 63] 
                ID Empleado: 1
                Usuario: pepe
                Nombre(s) = José
                Apellido Paterno: Flores
                Apellido Materno: Alvarado
                
09:35:34 PM: DEBUG [Empleado.py: 68] 
                ID Empleado: 2
                Usuario: jesgut
                Nombre(s) = Jesús
                Apellido Paterno: Gutiérrez
                Apellido Materno: Alvarado
                
09:35:34 PM: DEBUG [Empleado.py: 72] 
                ID Empleado: 1
                Usuario: None
                Nombre(s) = None
                Apellido Paterno: None
                Apellido Materno: None
                
09:44:29 PM: DEBUG [cursor_del_pool.py: 11] Inicio del método with __enter__
09:44:29 PM: DEBUG [Conexion.py: 29] Creación exitosa del pool de conexiones: <psycopg2.pool.SimpleConnectionPool object at 0x00000206C697B950>
09:44:29 PM: DEBUG [Conexion.py: 40] Conexion obtenida del pool: <connection object at 0x00000206C8852460; dsn: 'user=postgres password=xxx dbname=LibSys host=127.0.0.1 port=5432', closed: 0>
09:44:29 PM: DEBUG [cursor_del_pool.py: 17] Se ejecuta el método __exit__
09:44:29 PM: ERROR [cursor_del_pool.py: 20] Ocurrió una excepción, rollback realizado: name 'empleado' is not defined <class 'NameError'> <traceback object at 0x00000206C88E1EC0>
09:44:29 PM: DEBUG [Conexion.py: 46] Conexión regresada al pool de conexiones: <connection object at 0x00000206C8852460; dsn: 'user=postgres password=xxx dbname=LibSys host=127.0.0.1 port=5432', closed: 0>
09:46:04 PM: DEBUG [cursor_del_pool.py: 11] Inicio del método with __enter__
09:46:04 PM: DEBUG [Conexion.py: 29] Creación exitosa del pool de conexiones: <psycopg2.pool.SimpleConnectionPool object at 0x000001E45EBAB950>
09:46:04 PM: DEBUG [Conexion.py: 40] Conexion obtenida del pool: <connection object at 0x000001E460A42460; dsn: 'user=postgres password=xxx dbname=LibSys host=127.0.0.1 port=5432', closed: 0>
09:46:04 PM: DEBUG [cursor_del_pool.py: 17] Se ejecuta el método __exit__
09:46:04 PM: ERROR [cursor_del_pool.py: 20] Ocurrió una excepción, rollback realizado: no existe la relación «empleado»
LINE 1: INSERT INTO empleado(nombre_usuario, nombre, apellido_patern...
                    ^
 <class 'psycopg2.errors.UndefinedTable'> <traceback object at 0x000001E460AD88C0>
09:46:04 PM: DEBUG [Conexion.py: 46] Conexión regresada al pool de conexiones: <connection object at 0x000001E460A42460; dsn: 'user=postgres password=xxx dbname=LibSys host=127.0.0.1 port=5432', closed: 0>
12:14:06 AM: DEBUG [Usuario.py: 104] 
                ID Cliente: 1
                Usuario: jperez
                Nombre(s) = axel
                Apellido Paterno: PÃ©rez
                Apellido Materno: JuÃ¡rez
                DirecciÃ³n asociada: 1
                Correo: jperez@mail.com
                TelÃ©fono: 555 555 555
                Tarjeta: 1111 1111 1111 1111
                
12:14:06 AM: DEBUG [Usuario.py: 110] 
                ID Cliente: 2
                Usuario: jesgut
                Nombre(s) = JesÃºs
                Apellido Paterno: GutiÃ©rrez
                Apellido Materno: Alvarado
                DirecciÃ³n asociada: 2
                Correo: jesgut@mail.com
                TelÃ©fono: 555 555 444
                Tarjeta: 2222 2222 2222 2222
                
12:14:06 AM: DEBUG [Usuario.py: 114] 
                ID Cliente: 1
                Usuario: None
                Nombre(s) = None
                Apellido Paterno: None
                Apellido Materno: None
                DirecciÃ³n asociada: None
                Correo: None
                TelÃ©fono: None
                Tarjeta: None
                
12:53:43 AM: DEBUG [Direccion.py: 68] 
                ID Direccion: 2
                ID Cliente: 23312
                Direccion: Juan Gomez Albarran 18
                Ciudad: Ciudad de Mexico
                Municipio: Gustavo A Madero
                Codigo Postal: 78000
                
12:53:43 AM: DEBUG [Direccion.py: 73] 
                ID Direccion: 2
                ID Cliente: 23312
                Direccion: Juan Gomez Albarran 18
                Ciudad: Ciudad de Mexico
                Municipio: Gustavo A Madero
                Codigo Postal: 78000
                
12:53:43 AM: DEBUG [Direccion.py: 77] 
                ID Direccion: 2
                ID Cliente: None
                Direccion: None
                Ciudad: None
                Municipio: None
                Codigo Postal: None
                
01:52:01 PM: DEBUG [Tarjeta.py: 64] 
                Numero de Tarjeta: 543527364591827
                ID Cliente: 457876
                CVV: 577
                Fecha de Vencimiento: 23/12/29
                Banco: Santander
                
01:52:01 PM: DEBUG [Tarjeta.py: 69] 
                Numero de Tarjeta: 5354435634522345
                ID Cliente: 233
                CVV: 332
                Fecha de Vencimiento: 24/01/24
                Banco: Santander
                
01:52:01 PM: DEBUG [Tarjeta.py: 73] 
                Numero de Tarjeta: 5354435634522345
                ID Cliente: 233
                CVV: 332
                Fecha de Vencimiento: 24/01/24
                Banco: Santander
                
